version: '2'
services:
  webui:
    image: addteq/dockercoins-webui-aromito:$IMAGE_TAG
    links:
    - redis:redis
    ports:
    - 8000:80/tcp
    labels:
      io.rancher.container.pull_image: always
  rng:
    image: addteq/dockercoins-rng-aromito:$IMAGE_TAG
    labels:
      io.rancher.container.pull_image: always
  worker:
    image: addteq/dockercoins-worker-aromito:$IMAGE_TAG
    links:
    - rng:rng
    - hasher:hasher
    - redis:redis
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis
    labels:
      io.rancher.container.pull_image: always
  hasher:
    image: addteq/dockercoins-hasher-aromito:$IMAGE_TAG
    labels:
      io.rancher.container.pull_image: always
